singleServerConfig:
  address: "redis://localhost:6379"
  connectionPoolSize: 50
  connectionMinimumIdleSize: 10
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
